### ISSUE TITLE
Header is parsed incorrectly

### ISSUE THREAD

**Issue by GeorgeTailor** [pact-foundation/pact-js#1058]
### Software versions

_Please provide at least OS and version of pact-js_

- **OS**: _e.g. Mac OSX 12.6.3_
- **Consumer Pact library**:  `"@pact-foundation/pact": "10.4.1",`
- **Node Version**: `v16.13.1`

### Issue Checklist

Please confirm the following:

- [x] I have upgraded to the latest
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code and have [read](https://github.com/pact-foundation/pact-js/blob/master/docs/troubleshooting.md#test-fails-when-it-should-pass) the section on intermittent test failures
- [ ] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

Header should be parsed as a string, without default behaviour of splitting it by comma for every possible HTTP header.

### Actual behaviour

No matter what value is passed in a HTTP Header and what is its name it is always split if it has a comma in it.

### Steps to reproduce

Given the following code:
```
provider
            .given('assignments exist')
            .uponReceiving('a request for all assignments')
            .withRequest({
                method: 'GET',
                path: '/api/assignments',
                headers: {
                    Accept: 'application/json',
                    'X-Custom-Header': '{"id":"asd-asdasd-sd","additionalInfo":"some additional string"}'
                }
            })
            .willRespondWith({
                status: 200,
                headers: { 'Content-Type': 'application/json' },
                body:[]
            });

return provider.executeTest(async mockserver => {
            const response = await axios.get(`${mockserver.url}/api/assignments`, {
                headers: {
                     'X-Custom-Header': '{"id":"asd-asdasd-sd","additionalInfo":"some additional string"}'
                }
            });

            expect(response.data).toEqual([]);
        });
```

This test fails as pact splits the header by comma and tries to compare a part of invalid JSON between what was sent and what was received.
When the header is a string that does not contain any commas it works.

### Relevant log files

```
pact@10.4.1: Test failed for the following reasons:

  Mock server failed with the following mismatches:

        0) The following request was incorrect: 

                GET /api/assignments
            
                         1.0 Mismatch with header 'X-Custom-Header': Expected '' to be equal to '{"id":"asd-asdasd-sd"' for value at index 0
```

**Comment by TimothyJones** [comment]
I agree, this isn't the right behaviour.

**Comment by TimothyJones** [comment]
Possibly downgrading to 10.4.0 will allow you to work around this - as it looks like this commit is the culprit: https://github.com/pact-foundation/pact-js/commit/9c7939edc944d6736940215deacbe670ed33a29a (cc @mefellows)

**Comment by mefellows** [comment]
Yes, it's a bug thanks for raising it. Will need a bit of thinking, because that change was introduced to fix an upstream issue. I

**Comment by mefellows** [comment]
See also https://github.com/pact-foundation/pact-js/issues/1031

**Comment by TimothyJones** [comment]
Each header has different semantics, so maybe the solution is in specific matchers for different headers.

**Comment by mefellows** [comment]
Yes, that might be the way about it.

**Comment by GeorgeTailor** [comment]
I've tested it with `10.4.0` and it behaves the same for this particular case.

**Comment by mefellows** [comment]
It might be that the core is doing the split also. Out of interest, have you tried the 10.3.x branch? 

@rholshausen FYI

**Comment by rholshausen** [comment]
Currently, the matching assumes all headers follow the RFC multi-value format, unless they specifically don't (like Date has a comma in that should not be split).

Maybe we need to change it to assume headers are single values only, unless they are known multi-value headers. But then if someone creates a new custom header and expects it to be parsed as a multiple value one, it won't work. Maybe configuration to say a header is multi-value or not.

We can also wait for everyone to move over to HTTP2, where this problem goes away because the number of values are explicit in the protocol, and not in the encoded value.

**Comment by TimothyJones** [comment]
I’m on mobile so it’s not easy to check, but I thought the current RFC just says header values are a string? 

I think a specific type of matcher is probably the way to go here

**Comment by mefellows** [comment]
If my reading is correct, all of these [`registrations`](https://www.rfc-editor.org/rfc/rfc7231#section-8.3.2) potentially require special treatment. At the very least, `Accept` and all of the `Accept-*` accept a comma delimited list that need not be quoted. Anything with the [`#`](https://www.rfc-editor.org/rfc/rfc7230#section-7) ABNF notation extension is a comma-separated list, and unfortunately it seems hard to find a definitive list for these. `via` is another header that allows lists, but is not in that registry, so I'm sure that list is not definitive.

As a general rule, others (including unspecified headers) I believe are essentially a quoted string, which shouldn't be split. 

[This paragraph](https://datatracker.ietf.org/doc/html/rfc7231#section-8.3.2) I think is the key:

> Because commas (",") are used as a generic delimiter between
   field-values, they need to be treated with care if they are allowed
   in the field-value.  Typically, components that might contain a comma
   are protected with double-quotes using the quoted-string ABNF
   production.

**Comment by mefellows** [comment]
_(AH! I  forgot to hit send on it, just an FYI)_

> We can also wait for everyone to move over to HTTP2, where this problem goes away because the number of values are explicit in the protocol, and not in the encoded value.

I'm sure we'll be there very soon. Remember how quickly we all moved to IPv6? 

> Maybe we need to change it to assume headers are single values only, unless they are known multi-value headers. But then if someone creates a new custom header and expects it to be parsed as a multiple value one, it won't work. Maybe configuration to say a header is multi-value or not.

I've actually updated the Pact JS types to allow a header to be specified as a key with one or more values:

```ts
export declare type TemplateHeaders = {
  [header: string]:
    | string
    | MatchersV3.Matcher<string>
    | (MatchersV3.Matcher<string> | string)[];
};
```

This would make it explicit in the test itself (and means the various components of the headers may also be matched). When we call `pactffi_with_header_v2` it could then be assumed by the length of the resulting array type if it should be split or not?

**Comment by mslowiak** [comment]
> It might be that the core is doing the split also. Out of interest, have you tried the 10.3.x branch?
> 

@mefellows Unfortunately, it is not working as well for 10.0.x, 10.1.x, 10.2.x, 10.3.x.
Is it possible to get the rough ETA to fix this bug?

**Comment by mefellows** [comment]
Hi Marcin, thanks for clarifying. I suspect that's related to the previous bug that was addressed in the related change above.

I'll have to work with the team to come back to you on an ETA.

**Comment by mslowiak** [comment]
We are really keen on work more with Pact, but this is a blocker for us to utilize the tool.

Thanks for response, waiting then for more information 🙇‍♂️

**Comment by mefellows** [comment]
I've just added a label "smartbear supported" to the ticket, which will create an internal tracking issue in PactFlow's Jira (see that comment above). We will use this to prioritise and assign a team member to this task.

All activity will be public on this ticket. For now, sit tight and we'll update this ticket once we have more information on the next steps.

**Comment by mefellows** [comment]
@rholshausen does https://github.com/pact-foundation/pact-reference/issues/259 fix the underlying issue here? I think I just need to remove any comma splitting present in Pact JS and defer to the core for logic around multi valued headers, is that right?

**Comment by rholshausen** [comment]
No, it still follows the header grammar as documented in the RFC, but if you pass an array as the value, it should just use it as is. But I haven't tested this.

**Comment by quatros96** [comment]
We we have any update on this one?

**Comment by mefellows** [comment]
Failing example: https://github.com/pact-foundation/pact-js/compare/repro/pact-js-issue-1058?expand=1

**Comment by kroupacz** [comment]
Hello @mefellows 
did you really test the @GeorgeTailor's case when some custom "x-header" has stringified json as value?
Today I updated @pact-foundation/pact to version 12.1.0 and I believe it is still not working.

OS: e.g. Mac OSX 10.15.7
Consumer Pact library: "@pact-foundation/pact": "12.1.0",
Node Version: v18.14.0
Pact specification: V3

**Comment by kroupacz** [comment]
> It looks like the JSON object is being iterated on, and each key in the JSON structure is being converted into an index

@mefellows I don't think so. The JSON string is evidently split by comma, because "curly bracket" is included in logged string `"{"id":"asd-asdasd-sd"`
> 1.0 Mismatch with header 'X-Custom-Header': Expected '"{\"id\":\"asd-asdasd-sd\"' to be equal to '{"id":"asd-asdasd-sd"' for value at index 0

It's interesting that in my case even the real "x-info" request header (not header in interaction) is converted to array with empty string. But the real axios request contains correct "x-info" value. In your case there is splitted JSON string again.
> 2023-08-02T09:40:36.433335Z  INFO tokio-runtime-worker pact_matching: comparing to expected HTTP Request ( method: GET, path: /api/accounts/oem_user:12345, query: None, headers: Some({"x-info": [""]}), body: Missing )

**Comment by mefellows** [comment]
I've also shown it's not a problem in the rust core's standard interface, so it is either:

1. In our interop code layer
2. In the FFI interface

I still think it's likely to be (2), as we don't do much with the headers. Still looking.

**Comment by mefellows** [comment]
Confirmed it's an upstream issue (see link above) and https://github.com/pact-foundation/pact-js-core/compare/repro/pact-js-issue-1058?expand=1.

**Comment by joel35park** [comment]
Hi @mefellows , is this fixed now?

**Comment by mefellows** [comment]
It doesn't look to be based on the upstream issue, but you could run a quick test of my repro (bump to latest version of Pact JS) to test that out.

**Comment by kroupacz** [comment]
Hello @mefellows. I just tested the latest version of `@pact-foundation/pact@13` and I can confirm that the header parsing bug still exists and unfortunately we still have to use `@pact-foundation/pact@9` which is the last working version.

**Comment by kroupacz** [comment]
I'm guessing [this](https://github.com/pact-foundation/pact-reference/blob/791db1fcf2d112be54da2246b67fe8238f1c4cd1/rust/pact_models/src/headers.rs#L16) might be place where it's happening.

**Comment by kroupacz** [comment]
@mefellows This issue still blocks us from upgrading to a newer PactJS version than `@pact-foundation/pact@9`

**Comment by jainshravan123** [comment]
Hi @mefellows 

Is this fixed now? I am experiencing the same issue in v14 of @pact-foundation/pact.

**Comment by mefellows** [comment]
It's not high on the priority list to fix, albeit there is an issue.

@rholshausen do you have any pointers for somebody who might be game enough to contribute an upstream fix in https://github.com/pact-foundation/pact-reference/tree/master/rust?

**Comment by rholshausen** [comment]
The equivalent commit from Pact-JVM is https://github.com/pact-foundation/pact-jvm/commit/8c5b0b1da705b28c50787750fc27cd8aebbadd01

This may have to be done in the Mock server crate (https://github.com/pact-foundation/pact-core-mock-server), I have not investigated where the change is required to be made.

**Comment by hajekjiri** [comment]
Hi @mefellows, has there been any progress with this? We're still running `@pact-foundation/pact@9` because this issue prevents us from updating.

**Comment by mefellows** [comment]
The fix has been merged upstream, but I'll keep this open until it is released and the updated FFI components have been integrated here and demonstrated to fix the issue.

**Comment by kroupacz** [comment]
@mefellows Any news (besides the above) regarding this issue? It would be great if this bug could finally be completely fixed.

**Comment by mefellows** [comment]
I'd suggest sticking with the workaround for now - the upstream change requires more careful thinking and likely a refactor, due to how we interop between JS (all clients, in fact) and the C interface (unless the workaround doesn't work for you?).

This should at least get the tests working.

**Comment by kroupacz** [comment]
@mefellows
The mentioned workaround using the `equal()` method is only available starting from `MatchersV3`, and the option involving `value` definition with alphabetical sorting is not very useful for our use case.

Due to the above-mentioned issue, we are stuck on `@pact-foundation/pact` version `9.18.1`, where sending and validating such headers works without issues.

Because we are using this older version of `pact-js`, all our tests are written using `MatchersV2` (which lacks the `equal()` method). Refactoring thousands of tests into the new format all at once is simply not feasible for us.

The ideal solution for us would be a complete fix of the aforementioned bug in `pact-js`. This would allow us to upgrade to MatchersV3 (or even MatchersV4) and gradually migrate our tests to the new syntax over time.

**Comment by mefellows** [comment]
Obviously the ideal solution would be to fix the root cause! I'm just stating that this will be more complex than initially anticipated and I don't see us getting to it soon. 

The workarounds might not be perfect, but it would allow you to move forward with an upgrade. 

If you would be interested in looking into https://github.com/pact-foundation/pact-reference/issues/516#issuecomment-3926668082 further, that would be a great help, and we'd be happy to assist as you go.
